import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import theme from "../theme";
import PageSessionProvider from "../Providers/PageSessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  chatbar,
  main,
}: Readonly<{
  children: React.ReactNode;
  chatbar: React.ReactNode;
  main: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <PageSessionProvider>
            <Toaster position="top-center" toastOptions={{ duration: 4000 }} />
            <main className="min-h-screen">
                {children}
            </main>
          </PageSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
